---
name: Lullaby
main: kim\present\lullaby\Lullaby
version: 2.1.1
api: [3.0.0, 4.0.0]
author: PresentKim
website: https://github.com/PresentKim/Lullaby-PMMP
description: Healing when a player is lying in bed!
...
