---
name:             Lullaby
main:             presentkim\lullaby\LullabyMain
version:          1.1.0
api:              [3.0.0, 3.0.0-ALPHA10]
author:           PresentKim

permissions:
  lullaby.cmd:
    description:  Lullaby main command
    default:      op
    children:
      lullaby.cmd.heal:
        description:  Lullaby command - heal
        default:      op
      lullaby.cmd.delay:
        description:  Lullaby command - delay
        default:      op
      lullaby.cmd.lang:
        description:  Lullaby command - lang
        default:      op
      lullaby.cmd.reload:
        description:  Lullaby command - reload
        default:      op
      lullaby.cmd.save:
        description:  Lullaby command - save
        default:      op
...
