---
name:             Lullaby
main:             blugin\lullaby\Lullaby
version:          1.2.3
api:              [3.0.0, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
author:           PresentKim
website:          https://github.com/PMMPPlugin/Lullaby
description:      A plugin healing when a player is lying in bed

permissions:
  lullaby.cmd:
    description:  Lullaby main command
    default:      op
    children:
      lullaby.cmd.heal:
        description:  Lullaby command - heal
        default:      op
      lullaby.cmd.delay:
        description:  Lullaby command - delay
        default:      op
...
