# Advanced configuration file for Lullaby plugin
# Some of these settings are safe, others can break your server if modified incorrectly
# New settings/defaults won't appear automatically on this file when upgrading

settings:
  update-check: false

#Heal delay (Unit: second)
delay: 5

#Heal amount
heal: 1